// Write the REPL client into an app: `bun script/repl.ts '<code>'`. Generated
// rather than shipped, because it is a *client* - it runs in its own process,
// reads .runtime/port and .runtime/repl-token, and must not import the
// framework. One template, one file, so every app talks to its process the same
// way.
//
//   ctx.fns.procs.generate.repl({})              → <app>/script/repl.ts
//   ctx.fns.procs.generate.repl({ force: true }) → overwrite an existing one
import { chmod } from "node:fs/promises";

export default async function (ctx: Context, _session: Session | null, opts?: { force?: boolean }): Promise<{ written: string | null }> {
    const path = `${ctx.fns.procs.project.projectRoot({})}/script/repl.ts`;
    if (!opts?.force && await Bun.file(path).exists()) return { written: null };
    await Bun.write(path, CLIENT);
    await chmod(path, 0o755).catch(() => { /* an fs without modes */ });
    console.log(`[generate] ${path}`);
    return { written: path };
}

// The client, verbatim. Written with string concatenation rather than template
// literals so that nothing in here has to be escaped twice.
const CLIENT = String.raw`#!/usr/bin/env bun
// CLI client for the server-side REPL (POST /procs/repl) - generated by ctx.fns.procs.generate.repl.
//   bun script/repl.ts 'ctx.fns.procs.project.scan({})'
//   bun script/repl.ts -f snippet.ts
//   echo 'Object.keys(ctx.fns)' | bun script/repl.ts
const args = process.argv.slice(2);
let code: string;
if (args[0] === "-f" && args[1]) code = await Bun.file(args[1]).text();
else if (args.length > 0) code = args.join(" ");
else if (!process.stdin.isTTY) code = await Bun.stdin.text();
else { console.error("Usage: bun script/repl.ts '<code>' | -f <file> | - (stdin)"); process.exit(1); }

// A run writes its state into the project it works on, so the port and the token
// live under WORKDIR - the same variable the server was started with.
const workdir = process.env.WORKDIR?.replace(/^~(?=\/)/, process.env.HOME ?? "~") ?? ".";
const runtimeDir = workdir + "/.runtime";
const port = (await Bun.file(runtimeDir + "/port").text().catch(() => "")).trim();
if (!port) { console.error("No " + runtimeDir + "/port - is the server running?"); process.exit(1); }

// This run's token: a JWT with kind "repl", written 0600 beside the port, so it
// is readable on this machine and nowhere else.
const token = (await Bun.file(runtimeDir + "/repl-token").text().catch(() => "")).trim();

const res = await fetch("http://localhost:" + port + "/procs/repl", {
    method: "POST",
    headers: token ? { authorization: "Bearer " + token } : {},
    body: code,
});

const text = await res.text();
try {
    const data = JSON.parse(text);
    console.log(JSON.stringify(data, null, 2));
    if (!res.ok || data.error) process.exit(1);
} catch {
    console.log(text);
    if (!res.ok) process.exit(1);
}
`;
